spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userapi?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
  main:
    allow-circular-references: true